[package]
name = "amazeing-bin"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"

[dependencies]
amazeing = { version = "*", path = "../amazeing" }
colored = "3.0.0"
macroquad = "0.4.13"
rand = "0.9.0"

[[bin]]
name = "amazeing"
path = "src/main.rs"
